[project]
name = 'Decentralized-Public-Building-and-Construction-Code-Enforcement'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.construction-inspection]
path = 'contracts/construction-inspection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
